name: link-checker 
on:
  pull_request:

permissions:
  contents: read

jobs:
  link-check:
    name: Check Links
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Check links
      uses: lycheeverse/lychee-action@82202e5e9c2f4ef1a55a3d02563e1cb6041e5332  #v2.4.1
      with:
        fail: true
        lycheeVersion: v0.19.1
        args: --verbose --no-progress './**/*.md'


